- name: set up authentication and project
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: ansibleplaybookbundle.asb-modules

  post_tasks:
    - name: create project from namespace
      openshift_raw:
        api_version: v1
        kind: Project
        name: '{{ namespace }}'
        description: '{{ namespace }}'
        display_name: '{{ namespace }}'
        state: present
      environment:
        K8S_AUTH_KUBECONFIG: 'config'

    - name: deploy caffe2 apb
      include_role:
        name: caffe2
      vars:
        action: provision