- name: undeploy
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: ansibleplaybookbundle.asb-modules

  post_tasks:
    - name: undeploy caffe2 apb
      include_role:
        name: caffe2
      vars:
        action: deprovision

    - name: delete project
      openshift_raw:
        api_version: v1
        kind: Project
        name: '{{ namespace }}'
        state: absent
      environment:
        K8S_AUTH_KUBECONFIG: 'config'