---
- name: deploy caffe2 pod
  k8s_v1_pod:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    restart_policy: OnFailure
    labels:
      app: "{{ application_name }}"
      service: "{{ application_name }}"
    containers:
      - name: "{{ application_name }}"
        image: "{{ container_image_name }}"
        command: ["jupyter"]
        args: ["notebook", "--allow-root", "--port=8888", "--no-browser", "--ip=0.0.0.0"]
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility"
          - name: NVIDIA_REQUIRE_CUDA
            value: "cuda>=8.0"
        ports:
          - container_port: 8888
            protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU

- name: create service
  k8s_v1_service:
    name: "{{ application_name }}"
    namespace: '{{ namespace }}'
    labels:
      app: "{{ application_name }}"
      service: "{{ application_name }}"
    selector:
      app: "{{ application_name }}"
      service: "{{ application_name }}"
    ports:
      - name: jupyter
        port: 8888
        target_port: 8888

- name: create route
  openshift_v1_route:
    name: "{{ application_name }}"
    namespace: '{{ namespace }}'
    labels:
      app: "{{ application_name }}"
      service: "{{ application_name }}"
    to_name: "{{ application_name }}"
    spec_port_target_port: jupyter
    path: /notebooks/caffe2/caffe2/python/tutorials/Multi-GPU_Training.ipynb
